In [12]:
import numpy as np
import pandas as pd
import matplotlib as pyplot
import seaborn as sns
from statistics import mode

In [2]:
population=np.random.randint(10,30,50)

In [3]:
population

array([25, 29, 16, 24, 20, 10, 11, 24, 14, 29, 10, 23, 25, 22, 19, 18, 20,
       26, 24, 18, 14, 11, 27, 28, 10, 10, 12, 29, 29, 16, 17, 24, 11, 26,
       27, 24, 13, 16, 10, 17, 24, 17, 15, 29, 19, 25, 16, 11, 12, 23])

In [5]:
np.mean(population)

19.38

In [7]:
np.median(population)

19.0

In [8]:
mode(population)

24

In [9]:
print(f"mean of the population {np.mean(population)}")
print(f"median of the population {np.median(population)}")
print(f"mode of the population {mode(population)}")

mean of the population 19.38
median of the population 19.0
mode of the population 24


In [18]:
sample = np.random.choice(population,20)

In [19]:
sample

array([14, 20, 14, 29, 11, 14, 20, 29, 25, 29, 25, 19, 24, 19, 17, 29, 18,
       29, 15, 20])

In [20]:
print(f"mean of the sample {np.mean(sample)}")
print(f"median of the sample {np.median(sample)}")
print(f"mode of the sample {mode(sample)}")

mean of the sample 21.0
median of the sample 20.0
mode of the sample 29


In [21]:
sample1=np.random.choice(population,20)
sample2=np.random.choice(population,20)
sample3=np.random.choice(population,20)
sample4=np.random.choice(population,20)

In [22]:
print(sample1)
print(60*"=")
print(sample2)
print(60*"=")
print(sample3)
print(60*"=")
print(sample4)

[26 20 16 16 10 29 11 27 14 11 17 27 29 29 24 24 20 14 16 17]
[26 20 17 24 10 24 23 11 16 25 11 22 27 19 25 25 16 17 19 25]
[25 24 29 15 16 10 11 29 27 29 29 29 24 14 24 17 29 12 23 20]
[27 25 24 11 25 10 11 10 27 26 10 16 26 24 26 22 11 26 10 18]


In [23]:
mean_of_samples=[]

all_sample=[sample1,sample2,sample3,sample4]

for sample in all_sample:
    mean_of_samples.append(np.mean(sample))

In [24]:
mean_of_samples

[19.85, 20.1, 21.8, 19.25]

In [25]:
np.mean(mean_of_samples)

20.25